// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, email, hashed_password
) VALUES (
  $1, $2, $3
)
RETURNING id, username, email, hashed_password, created_at
`

type CreateUserParams struct {
	Username       string `json:"username"`
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}

type CreateUserRow struct {
	ID             int64              `json:"id"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	HashedPassword string             `json:"hashed_password"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.HashedPassword)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, hashed_password, created_at FROM users
WHERE id = $1 LIMIT 1
`

type GetUserRow struct {
	ID             int64              `json:"id"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	HashedPassword string             `json:"hashed_password"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const getUserWithAccounts = `-- name: GetUserWithAccounts :many
SELECT 
    u.id AS user_id, 
    u.username, 
    u.email, 
    u.hashed_password, 
    u.created_at AS user_created_at,
    a.id AS account_id, 
    a.balance, 
    a.currency, 
    a.created_at AS account_created_at
FROM users u
LEFT JOIN accounts a ON a.user_id = u.id
WHERE u.id = $1
`

type GetUserWithAccountsRow struct {
	UserID           int64              `json:"user_id"`
	Username         string             `json:"username"`
	Email            string             `json:"email"`
	HashedPassword   string             `json:"hashed_password"`
	UserCreatedAt    pgtype.Timestamptz `json:"user_created_at"`
	AccountID        pgtype.Int8        `json:"account_id"`
	Balance          pgtype.Int8        `json:"balance"`
	Currency         pgtype.Text        `json:"currency"`
	AccountCreatedAt pgtype.Timestamptz `json:"account_created_at"`
}

func (q *Queries) GetUserWithAccounts(ctx context.Context, id int64) ([]GetUserWithAccountsRow, error) {
	rows, err := q.db.Query(ctx, getUserWithAccounts, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWithAccountsRow
	for rows.Next() {
		var i GetUserWithAccountsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.HashedPassword,
			&i.UserCreatedAt,
			&i.AccountID,
			&i.Balance,
			&i.Currency,
			&i.AccountCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, hashed_password, created_at FROM users
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID             int64              `json:"id"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	HashedPassword string             `json:"hashed_password"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.HashedPassword,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
